name: C Build Check

on:
  push:
    paths:
      - '**.c'
  pull_request:
    paths:
      - '**.c'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install GCC compiler
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile all C solution files
      run: |
        find problems -name "*.c" | while read file; do
          echo "Compiling $file"
          gcc "$file" -o /tmp/$(basename "$file" .c).out || exit 1
        done
