name: C Build Check
permissions:
  contents: read

on:
  push:
    paths:
      - '**.c'
  pull_request:
    paths:
      - '**.c'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Install GCC compiler
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile all C solution files to object files
      run: |
        find problems -name "*.c" | while read file; do
          echo "Compiling $file"
          gcc -c "$file" -o /tmp/$(basename "$file" .c).o || exit 1
        done
