name: C++ Build Check

on:
  push:
    paths:
      - '**.cpp'
  pull_request:
    paths:
      - '**.cpp'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install g++ compiler
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile all C++ solution files to object files
      run: |
        find problems -name "*.cpp" | while read file; do
          echo "Compiling $file"
          # Compile with C++17 standard for modern features compatibility
          g++ -std=c++17 -c "$file" -o /tmp/$(basename "$file" .cpp).o || exit 1
        done
